/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 *
 * This product includes software developed at Datadog (https://www.datadoghq.com)  Copyright 2024 Datadog, Inc.
 */
package resourceindex

import "strings"

var ansibleModuleAliases = map[string]string{
	"aws_acm":                  "acm_certificate",
	"aws_api_gateway":          "api_gateway",
	"ec2_asg":                  "autoscaling_group",
	"ec2_lc":                   "autoscaling_launch_config",
	"aws_batch_job_definition": "batch_job_definition",
	"aws_codebuild":            "codebuild_project",
	"aws_config_aggregator":    "config_aggregator",
	"aws_config_rule":          "config_rule",
	"ec2_security_group":       "ec2_group",
	"aws_kms":                  "kms_key",
	"aws_s3":                   "s3_object",
	"aws_s3_cors":              "s3_cors",
	"aws_ses_identity_policy":  "ses_identity_policy",
}

var ansibleModuleNameKeys = map[string]string{
	"acm_certificate":                  "name_tag",
	"ansible_config":                   "name",
	"ansible_inventory":                "name",
	"ansible_playbook":                 "name",
	"ansible_task":                     "become_user",
	"api_gateway":                      "name",
	"apk":                              "name",
	"apt":                              "name",
	"archive":                          "dest",
	"assemble":                         "dest",
	"autoscaling_group":                "name",
	"autoscaling_launch_config":        "name",
	"azure_rm_adserviceprincipal":      "display_name",
	"azure_rm_aks":                     "name",
	"azure_rm_appgateway":              "name",
	"azure_rm_containerregistry":       "name",
	"azure_rm_cosmosdbaccount":         "name",
	"azure_rm_keyvault":                "vault_name",
	"azure_rm_lock":                    "name",
	"azure_rm_monitorlogprofile":       "name",
	"azure_rm_mysqlserver":             "name",
	"azure_rm_postgresqlconfiguration": "name",
	"azure_rm_postgresqlserver":        "name",
	"azure_rm_rediscache":              "name",
	"azure_rm_rediscachefirewallrule":  "name",
	"azure_rm_roledefinition":          "name",
	"azure_rm_securitygroup":           "name",
	"azure_rm_sqlfirewallrule":         "name",
	"azure_rm_sqlserver":               "name",
	"azure_rm_storageaccount":          "name",
	"azure_rm_storageblob":             "blob",
	"azure_rm_subnet":                  "name",
	"azure_rm_virtualmachine":          "name",
	"azure_rm_webapp":                  "name",
	"batch_job_definition":             "job_definition_name",
	"blockinfile":                      "path",
	"bower":                            "name",
	"bundler":                          "name",
	"cloudformation":                   "stack_name",
	"cloudformation_stack_set":         "name",
	"cloudfront_distribution":          "caller_reference",
	"cloudtrail":                       "name",
	"cloudwatchlogs_log_group":         "log_group_name",
	"codebuild_project":                "name",
	"config_aggregator":                "name",
	"config_rule":                      "name",
	"copy":                             "dest",
	"dnf":                              "name",
	"easy_install":                     "name",
	"ec2_ami":                          "name",
	"ec2_group":                        "name",
	"ec2_instance":                     "name",
	"ec2_launch_template":              "name",
	"ec2_vol":                          "name",
	"ec2_vpc_subnet":                   "cidr",
	"ecs_ecr":                          "name",
	"ecs_service":                      "name",
	"ecs_taskdefinition":               "family",
	"efs":                              "name",
	"elasticache":                      "name",
	"elb_application_lb":               "name",
	"elb_network_lb":                   "name",
	"file":                             "path",
	"gcp_bigquery_dataset":             "dataset_id",
	"gcp_compute_disk":                 "name",
	"gcp_compute_firewall":             "name",
	"gcp_compute_network":              "name",
	"gcp_compute_instance":             "name",
	"gcp_compute_ssl_policy":           "name",
	"gcp_compute_subnetwork":           "name",
	"gcp_container_cluster":            "name",
	"gcp_container_node_pool":          "name",
	"gcp_dns_managed_zone":             "name",
	"gcp_kms_crypto_key":               "name",
	"gcp_sql_instance":                 "name",
	"gcp_storage_bucket":               "name",
	"gem":                              "name",
	"get_url":                          "dest",
	"homebrew":                         "name",
	"htpasswd":                         "name",
	"iam_access_key":                   "user_name",
	"iam_group":                        "name",
	"iam_managed_policy":               "name",
	"iam_password_policy":              "name",
	"iam_policy":                       "policy_name",
	"iam_role":                         "name",
	"iam_user":                         "name",
	"ini_file":                         "path",
	"jenkins_plugin":                   "name",
	"kinesis_stream":                   "name",
	"kms_key":                          "alias",
	"lambda":                           "name",
	"lambda_policy":                    "function_name",
	"lineinfile":                       "path",
	"npm":                              "name",
	"openbsd_pkg":                      "name",
	"opensearch":                       "domain_name",
	"package":                          "name",
	"pacman":                           "name",
	"pear":                             "name",
	"pip":                              "name",
	"pkg5":                             "name",
	"pkgutil":                          "name",
	"portage":                          "package",
	"rds_instance":                     "db_instance_identifier",
	"rds_subnet_group":                 "name",
	"redshift":                         "identifier",
	"replace":                          "path",
	"route53":                          "record",
	"s3_bucket":                        "name",
	"s3_cors":                          "name",
	"s3_object":                        "object",
	"ses_identity_policy":              "identity",
	"slackpkg":                         "name",
	"sns_topic":                        "name",
	"sorcery":                          "name",
	"sqs_queue":                        "name",
	"sts_assume_role":                  "role_arn",
	"swdepot":                          "name",
	"template":                         "dest",
	"uri":                              "url",
	"user":                             "name",
	"win_chocolatey":                   "name",
	"win_copy":                         "dest",
	"win_template":                     "dest",
	"yarn":                             "name",
	"yum":                              "name",
	"zypper":                           "name",
}

func canonicalAnsibleModule(moduleName string) string {
	shortName := moduleName
	if separator := strings.LastIndex(shortName, "."); separator >= 0 {
		shortName = shortName[separator+1:]
	}
	if canonical, ok := ansibleModuleAliases[shortName]; ok {
		return canonical
	}
	return shortName
}

func ansibleModuleNameKey(canonical string) string {
	if key := ansibleModuleNameKeys[canonical]; key != "" {
		return key
	}
	return "name"
}
