/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 *
 * This product includes software developed at Datadog (https://www.datadoghq.com)  Copyright 2024 Datadog, Inc.
 */

// Package scan implements functions and helpers to ensure the proper scan of the specified files
package scan

import (
	"context"

	"github.com/DataDog/datadog-iac-scanner/internal/memwatch"
	"github.com/DataDog/datadog-iac-scanner/internal/metrics"
	"github.com/DataDog/datadog-iac-scanner/pkg/datadog"
	"github.com/DataDog/datadog-iac-scanner/pkg/engine"
	"github.com/DataDog/datadog-iac-scanner/pkg/engine/provider"
	"github.com/DataDog/datadog-iac-scanner/pkg/engine/source"
	"github.com/DataDog/datadog-iac-scanner/pkg/featureflags"
	"github.com/DataDog/datadog-iac-scanner/pkg/logger"
	"github.com/DataDog/datadog-iac-scanner/pkg/model"
	"github.com/DataDog/datadog-iac-scanner/pkg/parser"
	ansibleConfigParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/ansible/ini/config"
	ansibleHostsParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/ansible/ini/hosts"
	bicepParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/bicep"
	buildahParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/buildah"
	dockerParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/docker"
	protoParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/grpc"
	jsonParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/json"
	terraformParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/terraform"
	"github.com/DataDog/datadog-iac-scanner/pkg/parser/terraform/registry"
	cicdParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/yaml/cicd"
	yamlParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/yaml/default"
	"github.com/DataDog/datadog-iac-scanner/pkg/resolver"
	"github.com/DataDog/datadog-iac-scanner/pkg/resolver/helm"
	"github.com/DataDog/datadog-iac-scanner/pkg/runner"
	"github.com/DataDog/datadog-iac-scanner/pkg/scanner"
)

// Results represents a result generated by a single scan
type Results struct {
	Results        []model.Vulnerability
	ExtractedPaths provider.ExtractedPath
	Files          model.FileMetadatas
	FailedQueries  map[string]error
}

type executeScanParameters struct {
	services          []*runner.Service
	inspector         *engine.Inspector
	extractedPaths    provider.ExtractedPath
	moduleCleanup     func()
	remoteModulePaths []string
	registry          *registry.AddressRegistry
}

func (c *Client) initScan(ctx context.Context) (*executeScanParameters, error) {
	contextLogger := logger.FromContext(ctx)

	var extractedPaths provider.ExtractedPath
	var filePlatform map[string]string
	if c.inMemory {
		// Content-push (server) mode: the file set is the pushed paths. Skip the
		// disk walk + analyzer.Analyze the CLI path runs (it reads the repo from
		// disk and mutates ScanParams.Platform). Platforms come from the request
		// (ScanParams.Platform); content is read through c.fsys.
		extractedPaths = provider.ExtractedPath{Path: c.inMemoryPaths}
	} else {
		paths, fp, err := c.prepareAndAnalyzePaths(ctx)
		memwatch.Sample(ctx, memwatch.PhaseAnalyzePaths)
		if err != nil {
			contextLogger.Err(err).Msgf("failed to prepare and analyze paths %v", err)
			return nil, err
		}
		extractedPaths = paths
		filePlatform = fp
	}

	if len(extractedPaths.Path) == 0 {
		return nil, nil
	}

	// Create a fresh registry instance for this scan to avoid cross-scan pollution
	addressRegistry := registry.New()
	contextLogger.Info().Msg("Created new address registry for this scan")

	// Inject the registry into the tracker so the vulnerability builder can access it
	c.Tracker.SetTFPlanRegistry(addressRegistry)
	contextLogger.Info().Msg("Injected registry into tracker")

	paramsPlatforms := c.ScanParams.GetEffectivePlatforms()

	baselinePaths := extractedPaths.Path
	if len(filePlatform) > 0 {
		baselinePaths = make([]string, 0, len(filePlatform))
		for path := range filePlatform {
			baselinePaths = append(baselinePaths, path)
		}
	}
	moduleCleanup, remoteModulePaths, remoteSourceDirs, remoteModuleProvenance, err := c.resolveTerraformModulesForScan(
		ctx, paramsPlatforms, &extractedPaths, baselinePaths,
	)
	memwatch.Sample(ctx, memwatch.PhaseModuleResolve)
	if err != nil {
		return nil, err
	}
	initSucceeded := false
	defer func() {
		if initSucceeded {
			return
		}
		if moduleCleanup != nil {
			moduleCleanup()
		}
	}()

	useDifferentPlatformQueries(&paramsPlatforms)
	querySource, err := c.createQuerySource(ctx, paramsPlatforms)
	if err != nil {
		contextLogger.Err(err).Msgf("Failed to create query source")
		return nil, err
	}

	queryFilter := c.createQueryFilter()

	contextLogger.Info().Msgf("Preparing to inspect query source %v", querySource)

	metrics.Metric.Start("get_queries")
	inspector, err := engine.NewInspector(ctx,
		querySource,
		engine.DefaultVulnerabilityBuilder,
		c.Tracker,
		queryFilter,
		c.ScanParams.Config.RuleConfigs,
		c.ScanParams.RepoPath,
		c.ScanParams.UseOldSeverities,
		true,
		c.ScanParams.ParallelScanFlag,
		c.ScanParams.FlagEvaluator,
		c.fsys,
		c.ScanParams.DisableRuleIsolation,
		c.ScanParams.UseRulesCache,
	)
	metrics.Metric.Stop()
	memwatch.Sample(ctx, memwatch.PhaseGetQueries)
	if err != nil {
		return nil, err
	}

	if len(remoteSourceDirs) > 0 {
		inspector.SetRemoteModuleDirectories(remoteSourceDirs)
	}
	if len(remoteModuleProvenance) > 0 {
		inspector.SetRemoteModuleProvenance(remoteModuleProvenance)
	}
	inspector.SetExternalModulePaths(remoteModulePaths)

	contextLogger.Info().Msgf("Finished inspect query source %v", querySource)

	services, err := c.createService(
		ctx,
		inspector,
		extractedPaths.Path,
		remoteModulePaths,
		c.Tracker,
		c.Storage,
		paramsPlatforms,
		c.ScanParams.CloudProvider,
		c.FlagEvaluator,
		filePlatform,
		addressRegistry,
	)
	if err != nil {
		contextLogger.Err(err).Msgf("failed to create service %v", err)
		return nil, err
	}

	initSucceeded = true
	return &executeScanParameters{
		services:          services,
		inspector:         inspector,
		extractedPaths:    extractedPaths,
		moduleCleanup:     moduleCleanup,
		remoteModulePaths: remoteModulePaths,
		registry:          addressRegistry,
	}, nil
}

func (c *Client) createQuerySource(ctx context.Context, paramsPlatforms []string) (source.QueriesSource, error) {
	if c.querySourceFactory != nil {
		return c.querySourceFactory(ctx, paramsPlatforms)
	}
	fss := source.NewFilesystemSource(
		ctx,
		c.ScanParams.QueriesPath,
		paramsPlatforms,
		c.ScanParams.CloudProvider,
		c.ScanParams.LibrariesPath,
		c.ScanParams.ExperimentalQueries)
	if c.ScanParams.ChangedDefaultQueryPath {
		if c.ScanParams.ChangedDefaultLibrariesPath {
			// Explicit --libraries-path provided: use local libraries from disk.
			return fss, nil
		}
		// Local query path but no explicit libraries path: fetch libraries from the backend.
		libSource, err := source.NewDatadogSource(datadog.NewDatadogClient())
		if err != nil {
			return nil, err
		}
		return source.NewFilesystemSourceWithLibraryOverride(fss, libSource), nil
	}
	options := []source.DatadogSourceOption{
		source.WithWantedPlatforms(paramsPlatforms),
		source.WithWantedCloudProviders(c.ScanParams.CloudProvider),
	}
	if c.ScanParams.ChangedDefaultLibrariesPath {
		options = append(options, source.WithLibrarySource(fss))
	}
	return source.NewDatadogSource(
		datadog.NewDatadogClient(),
		options...,
	)
}

func (c *Client) executeScan(ctx context.Context) (*Results, error) {
	contextLogger := logger.FromContext(ctx)

	// Note: We now create a fresh registry instance per scan in initScan()
	// instead of clearing a global registry, which prevents race conditions

	executeScanParameters, err := c.initScan(ctx)

	if err != nil {
		contextLogger.Err(err).Msgf("failed to execute scan %v", err)
		return nil, err
	}

	if executeScanParameters == nil {
		return nil, nil
	}

	if executeScanParameters.moduleCleanup != nil {
		defer executeScanParameters.moduleCleanup()
	}

	contextLogger.Info().Msg("Scan initialized")

	contextLogger.Info().Msgf("Preparing to scan")

	if err = scanner.PrepareAndScan(
		ctx,
		c.ScanParams.ScanID, c.ScanParams.OpenAPIResolveReferences, c.ScanParams.MaxResolverDepth,
		executeScanParameters.services, c.FlagEvaluator); err != nil {
		contextLogger.Err(err).Msgf("failed to prepare and scan %v", err)
		return nil, err
	}

	contextLogger.Info().Msg("Scan finished")

	failedQueries := executeScanParameters.inspector.GetFailedQueries()

	results, err := c.Storage.GetVulnerabilities(ctx, c.ScanParams.ScanID)
	if err != nil {
		contextLogger.Err(err).Msgf("failed to get vulns %v", err)
		return nil, err
	}

	files, err := c.Storage.GetFiles(ctx, c.ScanParams.ScanID)
	if err != nil {
		contextLogger.Err(err).Msgf("failed to get files %v", err)
		return nil, err
	}

	return &Results{
		Results:        results,
		ExtractedPaths: executeScanParameters.extractedPaths,
		Files:          files,
		FailedQueries:  failedQueries,
	}, nil
}

func useDifferentPlatformQueries(platforms *[]string) {
	hasBicep := false
	hasARM := false
	for _, platform := range *platforms {
		if platform == "bicep" {
			hasBicep = true
		}
		if platform == "azureresourcemanager" {
			hasARM = true
		}
		if hasARM && hasBicep {
			break
		}
	}

	if hasBicep && !hasARM {
		*platforms = append(*platforms, "azureresourcemanager")
	}
}

func (c *Client) createQueryFilter() *source.QueryInspectorParameters {
	excludeQueries := source.QueryFilter{
		ByIDs:        c.ScanParams.Config.IgnoreRules,
		ByCategories: c.ScanParams.Config.IgnoreCategories,
		BySeverities: c.ScanParams.Config.IgnoreSeverities,
	}
	includeQueries := source.QueryFilter{
		ByIDs:        c.ScanParams.Config.OnlyRules,
		ByCategories: c.ScanParams.Config.OnlyCategories,
		BySeverities: c.ScanParams.Config.OnlySeverities,
	}

	queryFilter := source.QueryInspectorParameters{
		ExcludeQueries:      excludeQueries,
		IncludeQueries:      includeQueries,
		ExperimentalQueries: c.ScanParams.ExperimentalQueries,
		InputDataPath:       c.ScanParams.InputData,
		BomQueries:          c.ScanParams.BillOfMaterials,
		FlagEvaluator:       c.FlagEvaluator,
	}

	return &queryFilter
}

func (c *Client) createService(
	ctx context.Context,
	inspector *engine.Inspector,
	paths []string,
	remoteModulePaths []string,
	t runner.Tracker,
	store runner.Storage,
	types []string,
	cloudProviders []string,
	flagEvaluator featureflags.FlagEvaluator,
	filePlatform map[string]string,
	reg *registry.AddressRegistry) ([]*runner.Service, error) {
	var filesSource provider.SourceProvider
	if c.inMemory {
		allPaths := append([]string{}, paths...)
		allPaths = append(allPaths, remoteModulePaths...)
		filesSource = provider.NewMemorySourceProvider(c.fsys, allPaths,
			c.ScanParams.Config.IgnorePaths, c.ScanParams.Config.OnlyPaths)
	} else {
		fsSource, err := c.getFileSystemSourceProvider(ctx, paths)
		if err != nil {
			return nil, err
		}
		if len(c.walkInventory) > 0 {
			fsSource.SetPrebuiltWalk(c.walkInventory, c.chartRoots, c.contentCache)
		}
		fsSource.AddUnfilteredPaths(remoteModulePaths)
		filesSource = fsSource
	}
	combinedParserBuilder := parser.NewBuilder(ctx).
		WithFS(c.fsys).
		Add(&yamlParser.Parser{}).
		Add(terraformParser.NewWithParams(c.fsys, reg, c.ScanParams.TerraformVarsPath, &c.ScanParams.SCIInfo)).
		Add(&bicepParser.Parser{}).
		Add(&cicdParser.Parser{}).
		Add(&dockerParser.Parser{}).
		Add(&protoParser.Parser{}).
		Add(&buildahParser.Parser{}).
		Add(&ansibleConfigParser.Parser{}).
		Add(&ansibleHostsParser.Parser{})

	if c.ScanParams.ShouldScanTfPlans {
		combinedParserBuilder.Add(&jsonParser.Parser{})
	}

	combinedParser, err := combinedParserBuilder.Build(types, cloudProviders)
	if err != nil {
		return nil, err
	}

	// combinedResolver to be used to resolve files and templates
	builder := resolver.NewBuilder()
	if flagEvaluator.EvaluateWithOrg(featureflags.IacEnableKicsHelmResolver) {
		builder = builder.Add(ctx, &helm.Resolver{})
	}
	combinedResolver, err := builder.
		Build(ctx)
	if err != nil {
		return nil, err
	}

	services := make([]*runner.Service, 0, len(combinedParser))

	for _, p := range combinedParser {
		services = append(
			services,
			&runner.Service{
				SourceProvider: filesSource,
				Storage:        store,
				Parser:         p,
				Inspector:      inspector,
				Tracker:        t,
				Resolver:       combinedResolver,
				MaxFileSize:    c.ScanParams.MaxFileSizeFlag,
				Platforms:      types,
				FilePlatform:   filePlatform,
			},
		)
	}
	return services, nil
}

func (c *Client) getFileSystemSourceProvider(
	ctx context.Context, paths []string,
) (*provider.FileSystemSourceProvider, error) {
	var excludePaths []string
	if c.ScanParams.PayloadPath != "" {
		excludePaths = append(excludePaths, c.ScanParams.PayloadPath)
	}

	if len(c.ScanParams.Config.IgnorePaths) > 0 {
		excludePaths = append(excludePaths, c.ScanParams.Config.IgnorePaths...)
	}

	filesSource, err := provider.NewFileSystemSourceProvider(ctx, paths, excludePaths, c.ScanParams.Config.OnlyPaths)
	if err != nil {
		return nil, err
	}
	return filesSource, nil
}
