/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 *
 * This product includes software developed at Datadog (https://www.datadoghq.com)  Copyright 2024 Datadog, Inc.
 */

// Package scan implements functions and helpers to ensure the proper scan of the specified files
package scan

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"

	"golang.org/x/sync/errgroup"
	"golang.org/x/sync/singleflight"

	"github.com/DataDog/datadog-iac-scanner/internal/metrics"
	"github.com/DataDog/datadog-iac-scanner/pkg/datadog"
	"github.com/DataDog/datadog-iac-scanner/pkg/engine"
	"github.com/DataDog/datadog-iac-scanner/pkg/engine/provider"
	"github.com/DataDog/datadog-iac-scanner/pkg/engine/source"
	"github.com/DataDog/datadog-iac-scanner/pkg/featureflags"
	"github.com/DataDog/datadog-iac-scanner/pkg/logger"
	"github.com/DataDog/datadog-iac-scanner/pkg/model"
	"github.com/DataDog/datadog-iac-scanner/pkg/parser"
	ansibleConfigParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/ansible/ini/config"
	ansibleHostsParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/ansible/ini/hosts"
	bicepParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/bicep"
	buildahParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/buildah"
	dockerParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/docker"
	protoParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/grpc"
	jsonParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/json"
	terraformParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/terraform"
	tfmodules "github.com/DataDog/datadog-iac-scanner/pkg/parser/terraform/modules"
	tfresolver "github.com/DataDog/datadog-iac-scanner/pkg/parser/terraform/modules/resolver"
	cicdParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/yaml/cicd"
	yamlParser "github.com/DataDog/datadog-iac-scanner/pkg/parser/yaml/default"
	"github.com/DataDog/datadog-iac-scanner/pkg/resolver"
	"github.com/DataDog/datadog-iac-scanner/pkg/resolver/helm"
	"github.com/DataDog/datadog-iac-scanner/pkg/runner"
	"github.com/DataDog/datadog-iac-scanner/pkg/scanner"
)

const (
	moduleSourceRegistry       = "registry"
	seedGroupConcurrencyFactor = 4
)

// Results represents a result generated by a single scan
type Results struct {
	Results        []model.Vulnerability
	ExtractedPaths provider.ExtractedPath
	Files          model.FileMetadatas
	FailedQueries  map[string]error
}

type executeScanParameters struct {
	services       []*runner.Service
	inspector      *engine.Inspector
	extractedPaths provider.ExtractedPath
	moduleCleanups []func()
	// Remote module files are tracked separately so repo-scoped filters do not apply.
	remoteModulePaths []string
}

func (c *Client) initScan(ctx context.Context) (*executeScanParameters, error) {
	contextLogger := logger.FromContext(ctx)

	extractedPaths, err := c.prepareAndAnalyzePaths(ctx)
	if err != nil {
		contextLogger.Err(err).Msgf("failed to prepare and analyze paths %v", err)
		return nil, err
	}

	if len(extractedPaths.Path) == 0 {
		return nil, nil
	}

	paramsPlatforms := c.ScanParams.GetEffectivePlatforms()

	filteredFilesSource, err := c.getFileSystemSourceProvider(ctx, extractedPaths.Path, nil)
	if err != nil {
		return nil, err
	}
	moduleDiscoveryPaths := extractedPaths.Path
	if platformsIncludeTerraform(paramsPlatforms) {
		moduleDiscoveryPaths, err = filteredFilesSource.TerraformFiles(ctx)
		if err != nil {
			return nil, err
		}
	}
	chain := c.buildModuleResolverChain(ctx, moduleDiscoveryPaths)

	var remoteSourceDirs map[string]string
	var moduleCleanups []func()
	initSucceeded := false
	defer func() {
		if initSucceeded {
			return
		}
		for _, fn := range moduleCleanups {
			fn()
		}
	}()
	var remoteModulePaths []string
	if platformsIncludeTerraform(paramsPlatforms) {
		contextLogger.Info().Msg("Resolving remote Terraform modules...")
		maxDepth := c.ScanParams.ModuleMaxDepth
		moduleScanPaths, moduleExtractions, sourceDirs, cleanups := resolveRemoteModuleScanPaths(
			ctx, extractedPaths.Path, moduleDiscoveryPaths, chain, maxDepth)
		remoteSourceDirs = sourceDirs
		moduleCleanups = cleanups
		if len(moduleScanPaths) > 0 {
			contextLogger.Info().Msgf("Adding %d remote module file(s) to scan", len(moduleScanPaths))
			remoteModulePaths = moduleScanPaths
			for k, v := range moduleExtractions {
				extractedPaths.ExtractionMap[k] = v
			}
		}
	}
	useDifferentPlatformQueries(&paramsPlatforms)
	querySource, err := c.createQuerySource(ctx, paramsPlatforms)
	if err != nil {
		contextLogger.Err(err).Msgf("Failed to create query source")
		return nil, err
	}

	queryFilter := c.createQueryFilter()

	contextLogger.Info().Msgf("Preparing to inspect query source %v", querySource)

	metrics.Metric.Start("get_queries")
	inspector, err := engine.NewInspector(ctx,
		querySource,
		engine.DefaultVulnerabilityBuilder,
		c.Tracker,
		queryFilter,
		c.ScanParams.Config.RuleConfigs,
		c.ScanParams.RepoPath,
		c.ScanParams.UseOldSeverities,
		true,
		c.ScanParams.ParallelScanFlag,
		c.ScanParams.FlagEvaluator,
	)
	metrics.Metric.Stop()
	if err != nil {
		return nil, err
	}

	if len(remoteSourceDirs) > 0 {
		inspector.SetRemoteModuleDirectories(remoteSourceDirs)
	}
	inspector.SetExternalModulePaths(remoteModulePaths)

	contextLogger.Info().Msgf("Finished inspect query source %v", querySource)

	services, err := c.createService(
		ctx,
		inspector,
		extractedPaths.Path,
		remoteModulePaths,
		c.Tracker,
		c.Storage,
		paramsPlatforms,
		c.ScanParams.CloudProvider,
		c.FlagEvaluator,
	)
	if err != nil {
		contextLogger.Err(err).Msgf("failed to create service %v", err)
		return nil, err
	}

	initSucceeded = true
	return &executeScanParameters{
		services:          services,
		inspector:         inspector,
		remoteModulePaths: remoteModulePaths,
		extractedPaths:    extractedPaths,
		moduleCleanups:    moduleCleanups,
	}, nil
}

type resolvedEntry struct {
	res tfresolver.Resolution
	err error
}

type moduleGraphWalker struct {
	mu          sync.Mutex
	visited     map[string]bool
	resolved    map[string]resolvedEntry // persistent resolution cache (survives sf completion)
	paths       []string
	extractions map[string]model.ExtractedPathObject
	sourceDirs  map[string]string
	cleanups    []func()

	sf       singleflight.Group
	chain    tfresolver.Resolver
	maxDepth int

	parseMu    sync.Mutex
	parseCache map[string]map[string]tfmodules.ParsedModule
}

func newModuleGraphWalker(chain tfresolver.Resolver, maxDepth int) *moduleGraphWalker {
	return &moduleGraphWalker{
		visited:     make(map[string]bool),
		resolved:    make(map[string]resolvedEntry),
		extractions: make(map[string]model.ExtractedPathObject),
		sourceDirs:  make(map[string]string),
		chain:       chain,
		maxDepth:    maxDepth,
		parseCache:  make(map[string]map[string]tfmodules.ParsedModule),
	}
}

func (w *moduleGraphWalker) parseModulesInDir(
	ctx context.Context, dir string, allowedFiles map[string]bool,
) map[string]tfmodules.ParsedModule {
	key := filepath.Clean(dir) + "\x00" + allowedFilesCacheKey(allowedFiles)

	w.parseMu.Lock()
	if mods, ok := w.parseCache[key]; ok {
		w.parseMu.Unlock()
		return mods
	}
	w.parseMu.Unlock()

	var mods map[string]tfmodules.ParsedModule
	files, err := tfmodules.LoadTFFilesFromDir(dir)
	if err == nil && len(files) > 0 {
		withModuleParseSlot(ctx, func() {
			if parsed, parseErr := tfmodules.ParseTerraformModulesFromFiles(ctx, files, allowedFiles); parseErr == nil {
				mods = parsed
			}
		})
	}

	w.parseMu.Lock()
	w.parseCache[key] = mods
	w.parseMu.Unlock()
	return mods
}

func allowedFilesCacheKey(allowed map[string]bool) string {
	if allowed == nil {
		return "all"
	}
	paths := make([]string, 0, len(allowed))
	for p := range allowed {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	return strings.Join(paths, "\x00")
}

func (w *moduleGraphWalker) tryVisit(localPath string) bool {
	w.mu.Lock()
	defer w.mu.Unlock()
	if w.visited[localPath] {
		return false
	}
	w.visited[localPath] = true
	return true
}

func (w *moduleGraphWalker) addPaths(paths ...string) {
	if len(paths) == 0 {
		return
	}
	w.mu.Lock()
	w.paths = append(w.paths, paths...)
	w.mu.Unlock()
}

func (w *moduleGraphWalker) addExtraction(key string, val model.ExtractedPathObject) {
	w.mu.Lock()
	w.extractions[key] = val
	w.mu.Unlock()
}

func (w *moduleGraphWalker) addSourceDirs(entries map[string]string) {
	if len(entries) == 0 {
		return
	}
	w.mu.Lock()
	for k, v := range entries {
		w.sourceDirs[k] = v
	}
	w.mu.Unlock()
}

func (w *moduleGraphWalker) addCleanup(fn func()) {
	w.mu.Lock()
	w.cleanups = append(w.cleanups, fn)
	w.mu.Unlock()
}

func (w *moduleGraphWalker) resolveRemote(ctx context.Context, mod *tfmodules.ParsedModule) (tfresolver.Resolution, error) {
	resolveID := remoteResolveIdentity(mod)

	w.mu.Lock()
	if entry, ok := w.resolved[resolveID]; ok {
		w.mu.Unlock()
		return entry.res, entry.err
	}
	w.mu.Unlock()

	v, err, _ := w.sf.Do(resolveID, func() (interface{}, error) {
		// Re-check inside the closure: a concurrent goroutine may have finished
		// its singleflight call (and written to w.resolved) in the window between
		// our outer check above and this Do call.
		w.mu.Lock()
		if entry, ok := w.resolved[resolveID]; ok {
			w.mu.Unlock()
			return entry.res, entry.err
		}
		w.mu.Unlock()

		res, resolveErr := w.chain.Resolve(ctx, mod)
		w.mu.Lock()
		w.resolved[resolveID] = resolvedEntry{res: res, err: resolveErr}
		w.mu.Unlock()
		return res, resolveErr
	})
	if err != nil {
		return tfresolver.Resolution{}, err
	}
	return v.(tfresolver.Resolution), nil
}

var moduleTraversalConcurrency = tfresolver.FetchConcurrency

var moduleParseSem = make(chan struct{}, max(1, runtime.GOMAXPROCS(0)))

func withModuleParseSlot(ctx context.Context, fn func()) {
	select {
	case moduleParseSem <- struct{}{}:
		defer func() { <-moduleParseSem }()
		fn()
	case <-ctx.Done():
	}
}

func resolveRemoteModuleScanPaths(
	ctx context.Context,
	rootPaths []string,
	moduleDiscoveryPaths []string,
	chain tfresolver.Resolver,
	maxDepth int,
) (
	moduleScanPaths []string,
	moduleExtractions map[string]model.ExtractedPathObject,
	remoteSourceDirs map[string]string,
	cleanups []func(),
) {
	if maxDepth < 0 {
		return nil, nil, nil, nil
	}
	walker := newModuleGraphWalker(chain, maxDepth)
	seedGroups := walker.tfSeedGroups(ctx, rootPaths, moduleDiscoveryPaths)

	g, gCtx := errgroup.WithContext(ctx)
	g.SetLimit(runtime.GOMAXPROCS(0) * seedGroupConcurrencyFactor)
	for seedDir, allowedFiles := range seedGroups {
		g.Go(func() error {
			walker.traverse(gCtx, seedDir, allowedFiles, seedGroups, 0, false)
			return nil
		})
	}
	_ = g.Wait()

	return walker.paths, walker.extractions, walker.sourceDirs, walker.cleanups
}

func (w *moduleGraphWalker) tfSeedGroups(ctx context.Context, paths, moduleDiscoveryPaths []string) map[string]map[string]bool {
	allowedByDir := make(map[string]map[string]bool)
	for _, path := range moduleDiscoveryPaths {
		if !strings.HasSuffix(strings.ToLower(path), ".tf") {
			continue
		}
		dir := filepath.Dir(path)
		if allowedByDir[dir] == nil {
			allowedByDir[dir] = make(map[string]bool)
		}
		allowedByDir[dir][path] = true
	}
	groups := make(map[string]map[string]bool)
	for _, path := range paths {
		info, err := os.Stat(path)
		if err != nil {
			continue
		}
		if !info.IsDir() {
			if !strings.HasSuffix(strings.ToLower(path), ".tf") {
				continue
			}
			dir := filepath.Dir(path)
			if groups[dir] == nil {
				groups[dir] = make(map[string]bool)
			}
			groups[dir][path] = true
			continue
		}
		if len(moduleDiscoveryPaths) == 0 {
			groups[path] = nil
			continue
		}
		for dir, allowedFiles := range allowedByDir {
			if pathContainsDir(path, dir) {
				groups[dir] = allowedFiles
			}
		}
	}
	for child := range w.localModuleChildDirs(ctx, groups) {
		delete(groups, child)
	}
	return groups
}

func pathContainsDir(root, dir string) bool {
	rel, err := filepath.Rel(filepath.Clean(root), filepath.Clean(dir))
	return err == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(os.PathSeparator))
}

func (w *moduleGraphWalker) localModuleChildDirs(ctx context.Context, groups map[string]map[string]bool) map[string]bool {
	children := make(map[string]bool)
	for dir, allowedFiles := range groups {
		mods := w.parseModulesInDir(ctx, dir, allowedFiles)
		for src := range mods {
			if mods[src].IsLocal && groups[filepath.Clean(mods[src].AbsSource)] != nil {
				children[filepath.Clean(mods[src].AbsSource)] = true
			}
		}
	}
	return children
}

func (w *moduleGraphWalker) traverse(
	ctx context.Context,
	seed string,
	allowedFiles map[string]bool,
	repoAllowedDirs map[string]map[string]bool,
	depth int,
	inRemoteTree bool,
) {
	if w.maxDepth <= 0 || depth >= w.maxDepth {
		return
	}
	mods := w.parseModulesInDir(ctx, seed, allowedFiles)
	if mods == nil {
		return
	}

	for src := range mods {
		if !mods[src].IsLocal {
			continue
		}
		localDir := mods[src].AbsSource
		if localDir == "" {
			continue
		}
		childAllowedFiles := map[string]bool(nil)
		if !inRemoteTree {
			var ok bool
			childAllowedFiles, ok = repoAllowedDirs[filepath.Clean(localDir)]
			if !ok {
				continue
			}
		}
		if !w.tryVisit(localDir) {
			continue
		}
		// Remote-tree local modules are not covered by the repository scan.
		if inRemoteTree {
			w.addPaths(flatTFFilePaths(localDir)...)
		}
		w.traverse(ctx, localDir, childAllowedFiles, repoAllowedDirs, depth+1, inRemoteTree)
	}

	w.traverseRemoteMods(ctx, mods, repoAllowedDirs, depth)
}

func (w *moduleGraphWalker) traverseRemoteMods(
	ctx context.Context,
	mods map[string]tfmodules.ParsedModule,
	repoAllowedDirs map[string]map[string]bool,
	depth int,
) {
	var remoteMods []*tfmodules.ParsedModule
	for src := range mods {
		if !mods[src].IsLocal {
			m := mods[src]
			remoteMods = append(remoteMods, &m)
		}
	}
	if len(remoteMods) == 0 {
		return
	}

	contextLogger := logger.FromContext(ctx)
	g, gCtx := errgroup.WithContext(ctx)
	g.SetLimit(moduleTraversalConcurrency)
	for _, mod := range remoteMods {
		g.Go(func() error {
			contextLogger.Debug().Msgf("Fetching remote Terraform module %q", mod.Source)
			res, resolveErr := w.resolveRemote(gCtx, mod)
			if resolveErr != nil {
				contextLogger.Warn().Err(resolveErr).Msgf("Failed to resolve remote Terraform module %q", mod.Source)
				return nil
			}
			if res.LocalPath == "" {
				contextLogger.Warn().Msgf("Resolved remote Terraform module %q without a local path", mod.Source)
				return nil
			}
			contextLogger.Info().Msgf("Fetched remote Terraform module %q", mod.Source)

			// Caller-specific keys are needed even when the resolved path is shared.
			root := moduleCallRoot(mod)
			w.addSourceDirs(map[string]string{
				engine.RemoteModuleKey(root, mod.Source, mod.Version):               res.LocalPath,
				engine.RemoteModuleCallKey(root, mod.Source, mod.Version, mod.Name): res.LocalPath,
				engine.RemoteModuleCallKey(root, mod.Source, "", mod.Name):          res.LocalPath,
			})

			if !w.tryVisit(res.LocalPath) {
				return nil
			}
			if res.Cleanup != nil {
				w.addCleanup(res.Cleanup)
			}
			w.addPaths(flatTFFilePaths(res.LocalPath)...)
			w.addExtraction(res.LocalPath, model.ExtractedPathObject{
				Path:      canonicalModuleURL(mod.Source, mod.Version),
				LocalPath: false,
			})
			w.traverse(gCtx, res.LocalPath, nil, repoAllowedDirs, depth+1, true)
			return nil
		})
	}
	_ = g.Wait()
}

func moduleCallRoot(mod *tfmodules.ParsedModule) string {
	if mod.FileName == "" {
		return "."
	}
	return filepath.Clean(filepath.Dir(mod.FileName))
}

func remoteResolveIdentity(mod *tfmodules.ParsedModule) string {
	sourceType, _ := tfmodules.DetectModuleSourceType(mod.Source)
	// Versionless registry sources may resolve to different versions per call site.
	if sourceType == moduleSourceRegistry && mod.Version == "" {
		return engine.RemoteModuleCallKey(moduleCallRoot(mod), mod.Source, mod.Version, mod.Name)
	}
	// Pinned sources coalesce by source+version; canonicalGitModuleSource folds ".git" spellings.
	return canonicalGitModuleSource(mod.Source) + "\x00" + strings.TrimSpace(mod.Version)
}

func flatTFFilePaths(dir string) []string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	var paths []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasSuffix(strings.ToLower(name), ".tf") {
			paths = append(paths, filepath.Join(dir, name))
		}
	}
	return paths
}

// canonicalGitModuleSource folds ".git" spellings so identical modules share one resolve identity.
func canonicalGitModuleSource(moduleSource string) string {
	s := strings.TrimSpace(moduleSource)
	switch {
	case strings.Contains(s, ".git//"):
		return strings.Replace(s, ".git//", "//", 1)
	case strings.Contains(s, ".git?"):
		return strings.Replace(s, ".git?", "?", 1)
	case strings.HasSuffix(s, ".git"):
		return strings.TrimSuffix(s, ".git")
	}
	return s
}

func canonicalModuleURL(moduleSource, version string) string {
	out := canonicalGitModuleSource(moduleSource)
	st, scope := tfmodules.DetectModuleSourceType(out)
	if st == moduleSourceRegistry && scope == "public" {
		// Short form → registry.terraform.io/…
		if !strings.HasPrefix(out, "registry.terraform.io/") {
			out = "registry.terraform.io/" + out
		}
	}
	// Strip userinfo first so the @ version suffix is unambiguous.
	if idx := strings.Index(out, "@"); idx != -1 {
		if schemeEnd := strings.Index(out, "://"); schemeEnd != -1 && schemeEnd < idx {
			out = out[:schemeEnd+3] + out[idx+1:]
		}
	}
	if version != "" {
		out = out + "@" + version
	}
	return out
}

// buildModuleResolverChain returns:
//
//	local → .terraform/modules → manifest → LocalGitRef → BareGit → GoGetter
func (c *Client) buildModuleResolverChain(ctx context.Context, moduleDiscoveryPaths []string) *tfresolver.ChainResolver {
	contextLogger := logger.FromContext(ctx)

	resolvers := []tfresolver.Resolver{
		tfresolver.LocalResolver{},
		&tfresolver.DotTerraformResolver{RootDirs: dotTerraformRootDirs(moduleDiscoveryPaths)},
	}

	if c.ScanParams.ModulesManifestPath != "" {
		manifest, err := tfresolver.LoadManifest(c.ScanParams.ModulesManifestPath)
		if err != nil {
			contextLogger.Warn().Err(err).
				Msgf("Failed to load modules manifest %q; remote modules from manifest will be unresolved",
					c.ScanParams.ModulesManifestPath)
		} else {
			resolvers = append(resolvers, tfresolver.NewPrefetchedResolver(manifest))
		}
	}

	if !c.ScanParams.NoRemoteModules {
		resolvers = append(resolvers,
			tfresolver.NewLocalGitRefResolver(c.ScanParams.Path, ""),
			tfresolver.NewBareGitResolver(""),
		)
	}

	ggCfg := tfresolver.NewGoGetterConfig()
	ggCfg.Disabled = c.ScanParams.NoRemoteModules
	if t := c.ScanParams.ModuleFetchTimeout; t > 0 {
		ggCfg.FetchTimeout = t
		// Recreate the registry cache with the user-supplied timeout so the HTTP
		// client it holds respects the same deadline as go-getter fetches.
		ggCfg.RegistryCache = tfresolver.NewRegistryCache(ggCfg.FetchTimeout)
	}
	ggCfg.MaxTotalBytes = c.ScanParams.MaxModuleBytesTotal
	ggCfg.HostAllowlist = c.ScanParams.ModuleHostAllowlist

	if !ggCfg.Disabled {
		cache, err := tfresolver.NewModuleCache()
		if err != nil {
			contextLogger.Warn().Err(err).Msg("Module disk cache unavailable; fetched modules will not be cached")
		} else {
			ggCfg.Cache = cache
		}
	}

	resolvers = append(resolvers, tfresolver.NewGoGetterResolver(ggCfg))
	return tfresolver.NewChainResolver(resolvers...)
}

func dotTerraformRootDirs(paths []string) []string {
	seen := make(map[string]bool, len(paths))
	roots := make([]string, 0, len(paths))
	for _, p := range paths {
		root := terraformRootDir(p)
		if root == "" || seen[root] {
			continue
		}
		seen[root] = true
		roots = append(roots, root)
	}
	return roots
}

func terraformRootDir(path string) string {
	info, err := os.Stat(path)
	if err == nil && !info.IsDir() {
		path = filepath.Dir(path)
	}
	clean := filepath.Clean(path)
	for {
		if hasTerraformModulesManifest(clean) {
			return clean
		}
		parent := filepath.Dir(clean)
		if parent == clean {
			return filepath.Clean(path)
		}
		clean = parent
	}
}

func hasTerraformModulesManifest(dir string) bool {
	_, err := os.Stat(filepath.Join(dir, ".terraform", "modules", "modules.json"))
	return err == nil
}

func (c *Client) createQuerySource(ctx context.Context, paramsPlatforms []string) (source.QueriesSource, error) {
	if c.querySourceFactory != nil {
		return c.querySourceFactory(ctx, paramsPlatforms)
	}
	fss := source.NewFilesystemSource(
		ctx,
		c.ScanParams.QueriesPath,
		paramsPlatforms,
		c.ScanParams.CloudProvider,
		c.ScanParams.LibrariesPath,
		c.ScanParams.ExperimentalQueries)
	if c.ScanParams.ChangedDefaultQueryPath {
		return fss, nil
	}
	return source.NewDatadogSource(
		datadog.NewDatadogClient(),
		source.WithWantedPlatforms(paramsPlatforms),
		source.WithWantedCloudProviders(c.ScanParams.CloudProvider),
		source.WithLibrarySource(fss),
	)
}

func (c *Client) executeScan(ctx context.Context) (*Results, error) {
	contextLogger := logger.FromContext(ctx)
	executeScanParameters, err := c.initScan(ctx)

	if err != nil {
		contextLogger.Err(err).Msgf("failed to execute scan %v", err)
		return nil, err
	}

	if executeScanParameters == nil {
		return nil, nil
	}

	defer func() {
		for _, fn := range executeScanParameters.moduleCleanups {
			fn()
		}
	}()

	contextLogger.Info().Msg("Scan initialized")

	contextLogger.Info().Msgf("Preparing to scan")

	if err = scanner.PrepareAndScan(
		ctx,
		c.ScanParams.ScanID, c.ScanParams.OpenAPIResolveReferences, c.ScanParams.MaxResolverDepth,
		executeScanParameters.services, c.FlagEvaluator); err != nil {
		contextLogger.Err(err).Msgf("failed to prepare and scan %v", err)
		return nil, err
	}

	contextLogger.Info().Msg("Scan finished")

	failedQueries := executeScanParameters.inspector.GetFailedQueries()

	results, err := c.Storage.GetVulnerabilities(ctx, c.ScanParams.ScanID)
	if err != nil {
		contextLogger.Err(err).Msgf("failed to get vulns %v", err)
		return nil, err
	}

	files, err := c.Storage.GetFiles(ctx, c.ScanParams.ScanID)
	if err != nil {
		contextLogger.Err(err).Msgf("failed to get files %v", err)
		return nil, err
	}

	return &Results{
		Results:        results,
		ExtractedPaths: executeScanParameters.extractedPaths,
		Files:          files,
		FailedQueries:  failedQueries,
	}, nil
}

func platformsIncludeTerraform(platforms []string) bool {
	for _, p := range platforms {
		if strings.EqualFold(p, "terraform") {
			return true
		}
	}
	return false
}

func useDifferentPlatformQueries(platforms *[]string) {
	hasBicep := false
	hasARM := false
	for _, platform := range *platforms {
		if platform == "bicep" {
			hasBicep = true
		}
		if platform == "azureresourcemanager" {
			hasARM = true
		}
		if hasARM && hasBicep {
			break
		}
	}

	if hasBicep && !hasARM {
		*platforms = append(*platforms, "azureresourcemanager")
	}
}

func (c *Client) createQueryFilter() *source.QueryInspectorParameters {
	excludeQueries := source.QueryFilter{
		ByIDs:        c.ScanParams.Config.IgnoreRules,
		ByCategories: c.ScanParams.Config.IgnoreCategories,
		BySeverities: c.ScanParams.Config.IgnoreSeverities,
	}
	includeQueries := source.QueryFilter{
		ByIDs:        c.ScanParams.Config.OnlyRules,
		ByCategories: c.ScanParams.Config.OnlyCategories,
		BySeverities: c.ScanParams.Config.OnlySeverities,
	}

	queryFilter := source.QueryInspectorParameters{
		ExcludeQueries:      excludeQueries,
		IncludeQueries:      includeQueries,
		ExperimentalQueries: c.ScanParams.ExperimentalQueries,
		InputDataPath:       c.ScanParams.InputData,
		BomQueries:          c.ScanParams.BillOfMaterials,
		FlagEvaluator:       c.FlagEvaluator,
	}

	return &queryFilter
}

func (c *Client) createService(
	ctx context.Context,
	inspector *engine.Inspector,
	paths []string,
	remoteModulePaths []string,
	t runner.Tracker,
	store runner.Storage,
	types []string,
	cloudProviders []string,
	flagEvaluator featureflags.FlagEvaluator) ([]*runner.Service, error) {
	filesSource, err := c.getFileSystemSourceProvider(ctx, paths, remoteModulePaths)
	if err != nil {
		return nil, err
	}

	combinedParserBuilder := parser.NewBuilder(ctx).
		Add(&yamlParser.Parser{}).
		Add(terraformParser.NewDefaultWithParams(c.ScanParams.TerraformVarsPath, c.ScanParams.SCIInfo)).
		Add(&bicepParser.Parser{}).
		Add(&cicdParser.Parser{}).
		Add(&dockerParser.Parser{}).
		Add(&protoParser.Parser{}).
		Add(&buildahParser.Parser{}).
		Add(&ansibleConfigParser.Parser{}).
		Add(&ansibleHostsParser.Parser{})

	if c.ScanParams.ShouldScanTfPlans {
		combinedParserBuilder.Add(&jsonParser.Parser{})
	}

	combinedParser, err := combinedParserBuilder.Build(types, cloudProviders)
	if err != nil {
		return nil, err
	}

	// combinedResolver to be used to resolve files and templates
	builder := resolver.NewBuilder()
	if flagEvaluator.EvaluateWithOrg(featureflags.IacEnableKicsHelmResolver) {
		builder = builder.Add(ctx, &helm.Resolver{})
	}
	combinedResolver, err := builder.
		Build(ctx)
	if err != nil {
		return nil, err
	}

	services := make([]*runner.Service, 0, len(combinedParser))

	for _, p := range combinedParser {
		services = append(
			services,
			&runner.Service{
				SourceProvider: filesSource,
				Storage:        store,
				Parser:         p,
				Inspector:      inspector,
				Tracker:        t,
				Resolver:       combinedResolver,
				MaxFileSize:    c.ScanParams.MaxFileSizeFlag,
			},
		)
	}
	return services, nil
}

// getFileSystemSourceProvider applies repo path filters; remote module paths bypass them.
func (c *Client) getFileSystemSourceProvider(
	ctx context.Context, paths, remoteModulePaths []string,
) (*provider.FileSystemSourceProvider, error) {
	var excludePaths []string
	if c.ScanParams.PayloadPath != "" {
		excludePaths = append(excludePaths, c.ScanParams.PayloadPath)
	}
	if len(c.ScanParams.Config.IgnorePaths) > 0 {
		excludePaths = append(excludePaths, c.ScanParams.Config.IgnorePaths...)
	}

	filesSource, err := provider.NewFileSystemSourceProvider(ctx, paths, excludePaths, c.ScanParams.Config.OnlyPaths)
	if err != nil {
		return nil, err
	}
	if len(remoteModulePaths) > 0 {
		filesSource.AddUnfilteredPaths(remoteModulePaths)
	}
	return filesSource, nil
}
