# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: datadog-iac-scanner

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: datadog-iac-scanner
    main: ./cmd/scanner/
    binary: datadog-iac-scanner
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/DataDog/datadog-iac-scanner/internal/constants.Version={{ .Version }}
      - -X github.com/DataDog/datadog-iac-scanner/internal/constants.SCMCommit={{ .Commit }}
    env:
      - CGO_ENABLED=1
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
          - CGO_CFLAGS=-O2
          - CGO_CXXFLAGS=-O2
          - CGO_LDFLAGS=
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
          - CGO_CFLAGS=-O2
          - CGO_CXXFLAGS=-O2
          - CGO_LDFLAGS=
      - goos: windows
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
          - CGO_CFLAGS=-O2
          - CGO_CXXFLAGS=-O2
          - CGO_LDFLAGS=
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=o64-clang
          - CXX=o64-clang++
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=o64-clang
          - CXX=o64-clang++

archives:
  - ids: [datadog-iac-scanner]
    # Like the default template, but without version number
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 \"v1\") }}{{ .Amd64 }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

changelog:
  use: github-native

release:
  draft: true
  prerelease: auto
