package config

import (
	"errors"
	"fmt"
	"reflect"
	"regexp"
	"strings"

	"github.com/DataDog/datadog-iac-scanner/internal/constants"
	"gopkg.in/yaml.v3"
)

// iacSeverity is a custom type to ensure case-insensitive matching of one of the valid severities
type iacSeverity string

func (i *iacSeverity) UnmarshalYAML(value *yaml.Node) error {
	var str string
	if err := value.Decode(&str); err != nil {
		return err
	}
	candidate := strings.TrimSpace(str)
	for _, sev := range constants.AvailableSeverities {
		if strings.EqualFold(candidate, sev) && sev != "trace" {
			*i = iacSeverity(sev)
			return nil
		}
	}
	return makeUnmarshalError(value, "invalid severity: %q", str)
}

// iacCategory is a custom type to ensure case-insensitive matching of one of the valid categories
type iacCategory string

func (i *iacCategory) UnmarshalYAML(value *yaml.Node) error {
	var str string
	if err := value.Decode(&str); err != nil {
		return err
	}
	candidate := strings.TrimSpace(str)
	for cat := range constants.AvailableCategories {
		if strings.EqualFold(candidate, cat) {
			*i = iacCategory(cat)
			return nil
		}
	}
	return makeUnmarshalError(value, "invalid category: %q", str)
}

// makeUnmarshalError generates an error message that will be displayed as a YAML unmarshal error for the given node
func makeUnmarshalError(node *yaml.Node, format string, args ...any) error {
	var msg string
	if len(args) == 0 {
		msg = format
	} else {
		msg = fmt.Sprintf(format, args...)
	}
	return &yaml.TypeError{Errors: []string{fmt.Sprintf("line %d: %s", node.Line, msg)}}
}

// These messages are generated by the YAML library, and we want to rewrite them
var fieldNotFoundRe = regexp.MustCompile(`^line (\d+): field ([a-z-]+) not found in type (.*)`)
var repeatedMappingKeyRe = regexp.MustCompile(`^line (\d+): mapping key "([a-z-]+)" already defined at line (\d+)`)
var cannotUnmarshalRe = regexp.MustCompile(`^line (\d+): cannot unmarshal !!([a-z]+)( (.*))? into (.*)`)

// rewriteDecodeErrors changes some of the error messages to make them more user-friendly
func rewriteDecodeErrors(err error) error {
	var typeError *yaml.TypeError
	if !errors.As(err, &typeError) {
		return err
	}
	for i, e := range typeError.Errors {
		if found := fieldNotFoundRe.FindStringSubmatch(e); found != nil {
			// line 123: field use-rules not found in type config.iacGlobalConfig
			// ->
			// line 123: field `use-rules` is not valid in the `iac.global-config` section; maybe you should include it in the `iac` section instead
			msg := fmt.Sprintf("line %s: field `%s` is not valid", found[1], found[2])
			if location := rewriteLocation(found[3]); location != "" {
				msg += " in " + location
			}
			if isField[iacGlobalConfig](found[2]) {
				msg += "; maybe you should include it in the `iac.global-config` section instead"
			} else if isField[iacConfig](found[2]) {
				msg += "; maybe you should include it in the `iac` section instead"
			} else if isField[cfgFileYaml](found[2]) || isField[knownRootsCfgFile](found[2]) {
				msg += "; maybe you should include it in the top-level configuration instead"
			} else if isSastConfigField(found[2]) {
				msg += "; it looks like a datadog-static-analyzer configuration option, not a datadog-iac-scanner option"
			}
			typeError.Errors[i] = msg
		} else if found := repeatedMappingKeyRe.FindStringSubmatch(e); found != nil {
			// line 123: mapping key "use-rules" already defined at line 12
			// ->
			// line 123: field `use-rules` has already been set in line 12
			typeError.Errors[i] = fmt.Sprintf("line %s: field `%s` has already been set in line %s", found[1], found[2], found[3])
		} else if found := cannotUnmarshalRe.FindStringSubmatch(e); found != nil {
			// line 123: cannot unmarshal !!int `1234` into map
			// ->
			// line 123: value `1234` of type int is not valid here; a map was expected
			var msg string
			if found[3] == "" {
				msg = fmt.Sprintf("line %s: value of type %s is not valid here", found[1], found[2])
			} else {
				msg = fmt.Sprintf("line %s: value %s of type %s is not valid here", found[1], found[4], found[2])
			}
			if location := rewriteLocation(found[5]); location != "" {
				msg += fmt.Sprintf("; the content of %s was expected", location)
			} else {
				msg += fmt.Sprintf("; a %s was expected", found[5])
			}
			typeError.Errors[i] = msg
		}
	}
	return err
}

func rewriteLocation(where string) string {
	switch where {
	case "config.iacConfig":
		return "the `iac` section"
	case "config.iacGlobalConfig":
		return "the `iac.global-config` section"
	case "config.knownRootsCfgFile", "config.cfgFileYaml":
		return "the top-level configuration"
	}
	return ""
}

func isField[T any](name string) bool {
	t := reflect.TypeFor[T]()
	for i := 0; i < t.NumField(); i++ {
		if yt := t.Field(i).Tag.Get("yaml"); yt != "" {
			yt, _, _ = strings.Cut(yt, ",")
			if yt == name {
				return true
			}
		}
	}
	return false
}

func isSastConfigField(name string) bool {
	return name == "use-default-rulesets" ||
		name == "use-rulesets" ||
		name == "ignore-rulesets" ||
		name == "ruleset-configs" ||
		name == "rule-configs"
}
